// SPDX-License-Identifier: Apache-2.0
import { atlas, short } from './data';
import type { Location } from './navigation';

export function EvidenceView({ location, navigate }: { location: Location; navigate: (patch: Partial<Location>) => void }) {
  const selected = atlas.evidence.find((item) => item.id === location.evidence)!;
  return <section className="workspace evidence-workspace" aria-label="Recorded evidence">
    <aside className="outline"><span className="eyebrow">Retained records</span><h2>Evidence index</h2>{atlas.evidence.map((item) => <button key={item.id} className={`outline-item ${item.id === selected.id ? 'selected' : ''}`} aria-pressed={item.id === selected.id} onClick={() => navigate({ evidence: item.id })}><span>{item.id}</span><small>{item.title}</small></button>)}<p className="muted">Recorded result and current-source qualification are different questions.</p></aside>
    <div className="canvas-region"><div className="region-heading"><div><h1>{selected.title}</h1><p>{selected.id} · {selected.archived ? 'ARCHIVED baseline' : 'named digital workload'}</p></div><span className="result"><span className={selected.status === 'PASS' ? 'pass-glyph' : ''} aria-hidden="true">{selected.status === 'PASS' ? '✓' : '○'}</span> Recorded {selected.status}</span></div>
      <dl className="evidence-facts"><div><dt>Producing revision</dt><dd><a href={`${atlas.repository}/commit/${selected.revision}`} target="_blank" rel="noreferrer"><code>{short(selected.revision)}</code> ↗</a></dd></div><div><dt>Verification rung</dt><dd>{selected.rung}</dd></div><div><dt>Source correspondence</dt><dd>{selected.currentSourceMatches ? `${atlas.source.matchCount}/5 chip source hashes match E0018` : selected.archived ? 'Historical GPIO source, not current M1' : 'Earlier qualified source; not a current-source result'}</dd></div><div><dt>Scope</dt><dd>{selected.scope}</dd></div></dl>
      <h2>What this record supports</h2><p>{selected.id === 'E0010' ? 'The pinned M0 GPIO baseline completed official GDS, precheck and gate-level testing, with a clean rerun. Current M1 is a different design.' : selected.id === 'E0016' ? 'The retained public-pin UART TX 8N1 workload passed its declared digital verification ladder. This is not a complete UART implementation or current physical qualification.' : 'The retained bounded two-frame RX workload checks both frames and delivers the last byte after known-image HALT. Raw valid is capture, not acceptance.'}</p>
      <h2>What remains unqualified</h2><ul className="plain-list"><li>Current M1 CMOS5L fit, area and timing: NOT EVALUATED.</li><li>Complete retained-two-byte / continuous UART receive: NOT EVALUATED.</li><li>Silicon behavior and protocol breadth: NOT EVALUATED.</li><li>Owner understanding: separate learning record, not inferred from a PASS.</li></ul>
      <div className="record-links"><a href={selected.evidenceUrl} target="_blank" rel="noreferrer">Retained report and artifacts ↗</a>{selected.runUrl && <a href={selected.runUrl} target="_blank" rel="noreferrer">Producing Actions run ↗</a>}<a href={`${atlas.repository}/blob/${atlas.source.mainSnapshot}/docs/research/evaluation-contract.md`} target="_blank" rel="noreferrer">Evaluation contract ↗</a></div>
      <div className="trace-summary"><span className="eyebrow">Fail-closed qualification</span><p>Build-time export verifies current source hashes and E0018 manifest integrity. Missing or changed evidence cannot produce current-source PASS. This is a versioned snapshot, not a live GitHub status feed.</p></div>
    </div>
    <aside className="inspector"><span className="eyebrow">Accounting boundary</span><h2>CHIP_COMPLETE</h2><dl className="field-list"><div><dt>Declared state</dt><dd>{atlas.totalStateBits} bits · DERIVED</dd></div><div><dt>Generic cells</dt><dd>{atlas.genericScreen.cells ?? 'Unknown'} · MEASURED</dd></div><div><dt>Clock</dt><dd>{atlas.clockTargetHz / 1e6} MHz · TARGET</dd></div><div><dt>Allocation</dt><dd>{atlas.tileAllocation} tiles · TARGET</dd></div></dl><p>{atlas.genericScreen.scope}</p><h3>Producing tools · {selected.id}</h3><ul className="tool-list">{selected.tools.map((tool) => <li key={tool.name}><strong>{tool.name}</strong><span>{tool.version}</span></li>)}</ul>{selected.tools.length === 0 && <p>Producing tool identities unavailable.</p>}<h3>Evidence identity</h3><p>{atlas.source.evidenceIntegrity ? 'E0018 retained manifest hash and recorded stage outcomes validate.' : 'E0018 manifest integrity unavailable. No current-source PASS.'}</p><p>No fresh RTL simulation or physical rerun is implied by browsing this app.</p></aside>
  </section>;
}

export function Progress() {
  const physical = atlas.evidence.find((item) => item.id === 'E0010')!;
  const tx = atlas.evidence.find((item) => item.id === 'E0016')!;
  const rows = [
    ['M0 GPIO baseline', `${atlas.learning.m0Technical} · recorded technical gate`, `${physical.status} · archived M0 only`, atlas.learning.m0Fluency],
    ['UART TX 8N1', `${tx.status} · E0016 recorded`, 'NOT EVALUATED', 'NOT RECORDED'],
    ['Bounded last-byte RX', atlas.source.allSourceMatches ? 'PASS · E0018 matching source' : 'NOT VERIFIED · source/evidence mismatch', 'NOT EVALUATED', 'NOT RECORDED'],
    ['Two-byte host service', 'PR8 DRAFT / NOT MERGED', 'NOT EVALUATED', 'NOT RECORDED'],
    ['SPI / I2C / compiler', 'QUEUED', 'NOT EVALUATED', 'NOT RECORDED'],
  ];
  return <section className="progress-view" aria-label="Engineering and learning progress"><div className="region-heading"><div><h1>Progress without a percentage</h1><p>Workload × gate · engineering, physical evidence and learning stay separate</p></div><span className="eyebrow">Snapshot 2026-10-05</span></div>
    <div className="table-scroll"><table><caption className="sr-only">Separate technical, physical and owner learning gates</caption><thead><tr><th scope="col">Workload</th><th scope="col">Digital engineering</th><th scope="col">Physical closure</th><th scope="col">Owner learning</th></tr></thead><tbody>{rows.map((row) => <tr key={row[0]}>{row.map((cell, index) => index === 0 ? <th scope="row" key={index}>{cell}</th> : <td key={index}>{cell}</td>)}</tr>)}</tbody></table></div>
    <div className="progress-regions"><section><span className="eyebrow">Learning</span><h2>M0 owner fluency: {atlas.learning.m0Fluency}</h2><p>Technical gate {atlas.learning.m0Technical}. Automation never promotes human fluency. Engineering proceeds independently.</p><a href={`${atlas.repository}/blob/${atlas.source.mainSnapshot}/docs/learning/progress.json`} target="_blank" rel="noreferrer">Inspect learning record ↗</a></section><section><span className="eyebrow">Deferred integration</span><h2>PR8 stays separate</h2><p>{atlas.deferred.scope}</p><p><code>{short(atlas.deferred.head)}</code> · {atlas.deferred.status}</p><a href={atlas.deferred.url} target="_blank" rel="noreferrer">Inspect draft candidate ↗</a></section><section><span className="eyebrow">Research</span><h2>{atlas.hypotheses.every((item) => item.status === 'UNPROVEN') ? 'Hypotheses remain UNPROVEN' : 'Inspect hypothesis states'}</h2><p>{atlas.hypotheses.map((item) => `${item.id}: ${item.status}`).join(' · ')}. A usable visualization is not an architectural proof, physical qualification or protocol-completeness result.</p><a href={`${atlas.repository}/blob/${atlas.source.mainSnapshot}/docs/research-ledger.md`} target="_blank" rel="noreferrer">Open research ledger ↗</a></section></div>
  </section>;
}
